services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "./wait-for-it.sh", "elasticsearch:9200", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    # command: ["bash", "-lc", "./wait-for-it.sh db 5432 && ./wait-for-it.sh elasticsearch 9200 && python manage.py runserver 0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - elasticsearch
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=thinkland_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  postgres_data:
  es_data:
